# directory where resume input markdown files are stored
resumeMarkdownDir: "./example/markdown/"

# file of cover letter markdown
coverLetterMarkdown: "./example/cover-letter.md"

# order that resume markdown sections will appear in resume
resumeMarkdownFilesInOrder: ["header.md", "education.md", "skills.md", "experience.md"]

# filename of resume
resumeFileName: "example_resume"

# filename of cover letter
coverLetterFileName: "example_cover_letter"

# directory where files will be built to
buildDir: "./example/build/"
